title: Nicole A Montano
url: https://nicolemon.com
github_project: nicolemon/nicolemon.com
colorscheme: default-light
font-stack: josefin
markdown: kramdown
highlighter: rouge
sass:
    sass_dir: _sass
